version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n_app
    restart: unless-stopped
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_TUNNEL_URL}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - srlwordpress_wp_network

volumes:
  n8n_data:

networks:
  srlwordpress_wp_network:
    external: true